### PR TITLE
Use AbsaOSS k3d-action instead of kind in e2e GHA

### LINKED ISSUE #54: Replace kind with k3d action in test GHA workflow
Replace kind with [AbsaOSS k3d action](https://github.com/AbsaOSS/k3d-action) in test GHA workflow in order to speed up e2e test execution

### PR DESCRIPTION
**Pull request by somaritane**
Closes #54 
Signed-off-by: Timofey Ilinykh <timofey.ilinykh@absa.africa>

### CODE REVIEW

**Review by k0da — DISMISSED** [review]

**Comment by k0da** [comment]
@somaritane why you need traefik and LB?

**Comment by somaritane** [comment]
> @somaritane why you need traefik and LB?

@k0da it's just a temporary wild guess for now, as k3d action fails on checking the cluster connection right after its creation.
Now it is stuck on cluster creation, I wonder if this is related to the issue described here https://github.com/k8gb-io/k8gb/pull/537

**Comment by somaritane** [comment]
@k0da , downgrade to `ubuntu-18.04` environment in GH runner helped

**Review by kuritka — APPROVED** [review]
lgtm

**Review by k0da — APPROVED** [review]

**Pull request merged**
