### PR TITLE
Scan Docker images

### PR DESCRIPTION
**Pull request by k0da**
Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
Could you please provide some context on scanning approach and the tooling selection?

**Comment by k0da** [comment]
https://github.com/marketplace/actions/container-image-scan#container-scan 
They use Trivy, Dockle and CIS benchmarks

**Review by kuritka — CHANGES_REQUESTED** [review]
Why `go.mod` has changed when pipelines were updated ?

**Comment by k0da** [comment]
@kuritka to adress issues found by pipeline run

**Comment by kuritka** [comment]
> @kuritka to adress issues found by pipeline run

I see, probably `go mod tidy` was executed locally, so it removed all  `// indirect` modules and increased versions. 
I'm not sure if switching from k8s api `v0.18.8` to `v0.21.1` will be desired. At the very least, such change should be in a separate PR. Is pipeline running without go.mod / sum changes ?

**Comment by k0da** [comment]
@kuritka Ok, I cherry-picked this commit into a separate PR. Please check

**Review by kuritka — APPROVED** [review]
awesome! thx

**Pull request merged**
