### PR TITLE
Update deployment manifests

### PR DESCRIPTION
**Pull request by somaritane**
Sync deployment manifests to reflect the changes in the helm chart

### CODE REVIEW

**Review by k0da — DISMISSED** [review]
LGTM 👍

**Review by kuritka — DISMISSED** [review]

**Review by ytsarev — COMMENTED** [review]
@somaritane e2e tests are failing with rbac?

**Comment by somaritane** [comment]
> @somaritane e2e tests are failing with rbac?

@ytsarev, doesn't look like RBAC, still investigating.

**Comment by somaritane** [comment]
> > @somaritane e2e tests are failing with rbac?
> 
> @ytsarev, doesn't look like RBAC, still investigating.

After replacing kind with k3d action and downgrading GH runner environment to `ubuntu-18.04` e2e tests workflow is back to normal.

**Review by k0da — APPROVED** [review]

**Review by ytsarev — APPROVED** [review]
ok cool stuff

**Pull request merged**
