### PR TITLE
Upgrade CRDs version from v1beta1 to v1

### LINKED ISSUE #58: Change CRDs version from v1beta1 to v1
apiextensions.k8s.io/v1beta1 CustomResourceDefinition version is deprecated in k8s v1.16+ and unavailable in k8s v1.22+, therefore should be updated with apiextensions.k8s.io/v1

### PR DESCRIPTION
**Pull request by somaritane**
Fixes #58 
- Added CRD manifests update target with controller-gen
- Upgraded CRDs versions in manifests from v1beta1 to v1

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
What is the suggested migration/api version process? Any backward compatibility?

**Comment by k0da** [comment]
@ytsarev it is a apiextensions version update, object stays the same (it was v1 already)

**Comment by ytsarev** [comment]
@k0da i get this part, still what is the process ? is handled upstream smoothly between the versions?

**Comment by ytsarev** [comment]
@somaritane is this PR forgotten?

**Review by k0da — APPROVED** [review]

**Pull request closed without merging**
